window.cards = [
    { number: '1', imageUrl: 'pic/01.png'},
    { number: '2', imageUrl: 'pic/02.png' },
    { number: '3', imageUrl: 'pic/03.png' },
    { number: '4', imageUrl: 'pic/04.png'},
    { number: '5', imageUrl: 'pic/05.png' },
    { number: '6', imageUrl: 'pic/06.png' },
    { number: '7', imageUrl: 'pic/07.png'},
    { number: '8', imageUrl: 'pic/08.png' },
    { number: '9', imageUrl: 'pic/09.png' },
    { number: '10', imageUrl: 'pic/10.png'},
    { number: '11', imageUrl: 'pic/11.png' },
    { number: '12', imageUrl: 'pic/12.png' },
    { number: '13', imageUrl: 'pic/13.png'},
    { number: '14', imageUrl: 'pic/14.png' },
    { number: '15', imageUrl: 'pic/15.png' },
    { number: '16', imageUrl: 'pic/16.png'},
    { number: '17', imageUrl: 'pic/17.png' },
    { number: '18', imageUrl: 'pic/18.png' },
    { number: '19', imageUrl: 'pic/19.png'},
    { number: '20', imageUrl: 'pic/20.png' },
    { number: '21', imageUrl: 'pic/21.png' },
    { number: '22', imageUrl: 'pic/22.png'},
    { number: '23', imageUrl: 'pic/23.png' },
    { number: '24', imageUrl: 'pic/24.png' },
    { number: '25', imageUrl: 'pic/25.png'},
    { number: '26', imageUrl: 'pic/26.png' },
    { number: '27', imageUrl: 'pic/27.png' },
    { number: '28', imageUrl: 'pic/28.png'},
    { number: '29', imageUrl: 'pic/29.png' },
    { number: '30', imageUrl: 'pic/30.png' },
    { number: '31', imageUrl: 'pic/31.png'}    
];


